FROM balenalib/amd64-debian-node:12.22-bullseye-run

ARG PLEXAMP_VERSION=v4.5.0-beta.7

ENV PLEXAMP_VERSION=$PLEXAMP_VERSION

RUN apt -y update \
  && apt -y upgrade \
  && apt -y install --no-install-recommends bzip2 alsa-utils pulseaudio pulseaudio-utils

RUN groupadd -g 1001 plexamp \
  && useradd -g 1001 -u 1001 -s /bin/bash -d /home/plexamp -G audio,video,render plexamp

RUN mkdir /app \
  && curl -o /tmp/plexamp-linux.tbz2 -L https://plexamp.plex.tv/headless/Plexamp-Linux-headless-${PLEXAMP_VERSION}.tar.bz2 \
  && tar -jxvf /tmp/plexamp-linux.tbz2 -C /app \
  && rm -f /tmp/*.tbz2 \
  && chown -R 1001:1001 /app \
  && apt-get -y clean autoclean \
  && apt-get autoremove -y 


# COPY confs/asound.conf /etc/asound.conf
# COPY confs/pulse-client.conf /etc/pulse/client.conf

VOLUME /home/plexamp
USER 1001
WORKDIR /app/plexamp

CMD ["node", "js/index.js"]
